#!/usr/bin/env python3
"""
Enterprise Bus Validator - Log and Database Decryption Utility Tool
===================================================================

This tool decrypts:
  1. Encrypted Log Files (.enc) generated by EncryptedLogger.kt
  2. Encrypted Database Backups (.db.enc) generated by DatabaseBackupManager.kt
  3. SQLCipher Encrypted Databases (.db) generated by Room / SQLCipher Android

Master Keys:
  - AES-256 Log & DB Key: "EnterpriseBusValidatorAESKey2026"
  - SQLCipher Passphrase: "EnterpriseBusValidatorSQLCipherPassphrase2026"

Usage:
  # Decrypt an encrypted log file:
  python3 tools/decrypt_logs_and_db.py --log path/to/log_1722500000.enc --out path/to/log_decrypted.txt

  # Decrypt an encrypted DB backup file (.db.enc):
  python3 tools/decrypt_logs_and_db.py --db path/to/db_backup.db.enc --out path/to/decrypted_database.db

  # Decrypt a raw SQLCipher DB file using sqlite3/sqlcipher:
  python3 tools/decrypt_logs_and_db.py --sqlcipher path/to/bus_validator_encrypted.db --out path/to/plain.db
"""

import sys
import os
import base64
import argparse
import subprocess

# AES-256 GCM Key (32 bytes)
AES_MASTER_KEY = b"EnterpriseBusValidatorAESKey2026"
SQLCIPHER_PASSPHRASE = "EnterpriseBusValidatorSQLCipherPassphrase2026"

def decrypt_aes_gcm(encrypted_bytes: bytes, key: bytes = AES_MASTER_KEY) -> bytes:
    """Decrypts raw bytes encrypted with AES-256-GCM (12-byte IV + Ciphertext + Tag)."""
    try:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
        iv = encrypted_bytes[:12]
        ciphertext_and_tag = encrypted_bytes[12:]
        aesgcm = AESGCM(key)
        return aesgcm.decrypt(iv, ciphertext_and_tag, None)
    except ImportError:
        # Fallback to PyCryptodome if cryptography is not installed
        try:
            from Crypto.Cipher import AES
            iv = encrypted_bytes[:12]
            # In AES-GCM, the last 16 bytes are the auth tag
            tag = encrypted_bytes[-16:]
            ciphertext = encrypted_bytes[12:-16]
            cipher = AES.new(key, AES.MODE_GCM, nonce=iv)
            return cipher.decrypt_and_verify(ciphertext, tag)
        except ImportError:
            print("ERROR: Neither 'cryptography' nor 'pycryptodome' Python packages are installed.")
            print("Please install via: pip install cryptography")
            sys.exit(1)

def decrypt_log_file(input_file: str, output_file: str):
    """Decrypts a line-by-line Base64 AES-GCM encrypted log file."""
    if not os.path.exists(input_file):
        print(f"Error: Input file '{input_file}' not found.")
        sys.exit(1)

    decrypted_lines = []
    success_count = 0
    fail_count = 0

    with open(input_file, "r", encoding="utf-8") as f:
        for line_num, line in enumerate(f, 1):
            line_str = line.strip()
            if not line_str:
                continue
            try:
                raw_bytes = base64.b64decode(line_str)
                decrypted_bytes = decrypt_aes_gcm(raw_bytes)
                decrypted_lines.append(decrypted_bytes.decode("utf-8", errors="replace"))
                success_count += 1
            except Exception as e:
                fail_count += 1
                decrypted_lines.append(f"[DECRYPTION FAILED line {line_num}: {e}]\n")

    out_path = output_file or (input_file + ".decrypted.txt")
    with open(out_path, "w", encoding="utf-8") as f:
        f.writelines(decrypted_lines)

    print(f"SUCCESS: Decrypted {success_count} log entries ({fail_count} failed) -> Saved to '{out_path}'")

def decrypt_db_backup(input_file: str, output_file: str):
    """Decrypts an AES-256-GCM encrypted binary database backup file."""
    if not os.path.exists(input_file):
        print(f"Error: Input file '{input_file}' not found.")
        sys.exit(1)

    with open(input_file, "rb") as f:
        encrypted_bytes = f.read()

    print(f"Decrypting binary database backup ({len(encrypted_bytes)} bytes)...")
    decrypted_bytes = decrypt_aes_gcm(encrypted_bytes)

    out_path = output_file or (input_file.replace(".enc", "") + ".decrypted.db")
    with open(out_path, "wb") as f:
        f.write(decrypted_bytes)

    print(f"SUCCESS: Decrypted database backup -> Saved to '{out_path}' ({len(decrypted_bytes)} bytes)")

def decrypt_sqlcipher_db(input_file: str, output_file: str):
    """Converts a SQLCipher encrypted database to plain unencrypted SQLite DB using sqlcipher CLI."""
    if not os.path.exists(input_file):
        print(f"Error: Input file '{input_file}' not found.")
        sys.exit(1)

    out_path = output_file or (input_file + ".plain.db")
    if os.path.exists(out_path):
        os.remove(out_path)

    # Check if sqlcipher binary is available in PATH
    sqlcipher_cmd = "sqlcipher"
    check = subprocess.run(["which", sqlcipher_cmd], capture_output=True)
    if check.returncode != 0:
        print(f"Notice: 'sqlcipher' command not found in PATH.")
        print(f"SQLCipher Passphrase for '{input_file}': {SQLCIPHER_PASSPHRASE}")
        print(f"To convert on macOS using brew: 'brew install sqlcipher'")
        print(f"Manual CLI command:")
        print(f"  sqlcipher {input_file} \"PRAGMA key = '{SQLCIPHER_PASSPHRASE}'; ATTACH DATABASE '{out_path}' AS plaintext KEY ''; SELECT sqlcipher_export('plaintext'); DETACH DATABASE plaintext;\"")
        return

    sql_script = f"PRAGMA key = '{SQLCIPHER_PASSPHRASE}'; ATTACH DATABASE '{out_path}' AS plaintext KEY ''; SELECT sqlcipher_export('plaintext'); DETACH DATABASE plaintext;"
    res = subprocess.run([sqlcipher_cmd, input_file, sql_script], capture_output=True, text=True)
    if res.returncode == 0:
        print(f"SUCCESS: Converted SQLCipher DB to plain SQLite DB -> Saved to '{out_path}'")
    else:
        print(f"Error executing sqlcipher export: {res.stderr}")

def main():
    parser = argparse.ArgumentParser(
        description="Enterprise Bus Validator Log & Database Decryption Utility Tool",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--log", help="Path to encrypted log file (.enc)")
    parser.add_argument("--db", help="Path to encrypted database backup file (.db.enc)")
    parser.add_argument("--sqlcipher", help="Path to SQLCipher encrypted database file (.db)")
    parser.add_argument("--out", "-o", help="Output file path")

    args = parser.parse_args()

    if not any([args.log, args.db, args.sqlcipher]):
        parser.print_help()
        sys.exit(0)

    if args.log:
        decrypt_log_file(args.log, args.out)
    elif args.db:
        decrypt_db_backup(args.db, args.out)
    elif args.sqlcipher:
        decrypt_sqlcipher_db(args.sqlcipher, args.out)

if __name__ == "__main__":
    main()
